### ISSUE TITLE
Text need to come below the image

### ISSUE THREAD

**Issue by ashwinkalyanpur** [jasonday/printThis#63] opened 2016-03-30 09:05 UTC
Hello,
I have attached the PDF wanted the text container to come below the image.
Having issue the text container is overlapping.
I am using print this version
 printThis v1.4
 * @desc Printing plug-in for jQuery
 * @author Jason Day
 *
 * Resources (based on) :
 *              jPrintArea: http://plugins.jquery.com/project/jPrintArea
 *              jqPrint: https://github.com/permanenttourist/jquery.jqprint
 *              Ben Nadal: http://www.bennadel.com/blog/1591-Ask-Ben-Print-Part-Of-A-Web-Page-With-jQuery.htm
 *
 * Licensed under the MIT licence:
 *              http://www.opensource.org/licenses/mit-license.php
 *
 * (c) Jason Day 2014
[Ikea Damage Item Marking.pdf](https://github.com/jasonday/printThis/files/195157/Ikea.Damage.Item.Marking.pdf)
and playing around the css and Jquery 

CSS:-
.viewport{
	position:relative !important;
	margin:0 auto;
	width:100%;
	text-align:center;
	height:100%;
	display:block;
	clear:both;
}
.printNotes {
    position: relative !important;
    height: 100%;
    margin:300px 30px auto;
    width: 100%;
    top:400px;
    display:block;
    clear:both;
}
JQuery:-
 	document.getElementById("print"+i).onclick=function(){
		saveToDB();
		$(".viewport, #imgNote").printThis();
		$("#imgNote").addClass('printNotes');
		$(".viewport").addClass('viewportimg');
		$(".edit").parent().removeClass("addBgColor");
		// $("#imgNote").removeClass('showcontent');
	}

add the path
PrintThis.js
// defaults
   $.fn.printThis.defaults = {
        debug: false, // show the iframe for debugging
        importCSS: true, // import parent page css
        printContainer: true, // print outer container/$.selector
        loadCSS: "css/images_upload/print.css", // load an additional css file
        pageTitle: "Ikea Damage Item Marking", // add title to print page
        removeInline: false, // remove all inline styles
        printDelay: 500, // variable print delay
        header: "", // prefix to html
        formValues: true // preserve input/form values
    };

**Comment by jasonday** [comment] 2016-03-31 01:01
A couple of questions:

Have you tried adding CSS to specifically adjust the layout the way you want?

When you call printThis, you have several other jQuery functions immediately after - are these part of your print detail?

**Comment by ashwinkalyanpur** [comment] 2016-03-31 05:49
Yes by default the image and the text content has position absolute it comes left 10px for image and position absolute right 10px as need to show next to next there are few restriction in the other plugin in image editor for positioning so .
I am adding the class to replace when i do onclick event in Jquery 
$("#imgNote").addClass('printNotes'); by adding this for text position will be relative to come below the image even tried adding position absolute and top 400 px as the image height is 350px to achieve it below the image.

$(".viewport").addClass('viewportimg'); tryed add css in print.css with viewportimg replacing the viewport css but still the text come above the image as attached image

**Comment by ashwinkalyanpur** [comment] 2016-04-01 05:37
Hi Jas,
Found the solution and fixed this for chrome browser.
But this is not working in Mozilla FF is there any separate css to be defined for the position for FF.

**Comment by jasonday** [comment] 2016-04-01 12:28
I don't think the issue is the browser, but is your code. You have a CSS conflict somewhere, and without seeing a working version of the code, I am unable to help you debug. This isn't an issue of the plugin, so I am closing this ticket. If you put together a working example, or can give me a url, I'll take a look. 

Good luck.

**Closed by jasonday** 2016-04-01 12:28 UTC
