### ISSUE TITLE
broken with firefox 67?

### ISSUE THREAD

**Issue by mcanepa** [jasonday/printThis#176] opened 2019-05-29 13:39 UTC
I was using this plugin just fine, then all of a sudden it stopped working. This happened right after firefox updated from 66.0.5 to 67.

The problem is that print styles aren't applying.

So I've uninstalled v67 and re installed 66 and the plugin worked again. As soon as firefox updated again the plugin failed.

Something important to notice is that if I test the script on localhost, then styles are applyied...but if the same code is tested online then the styles are not shown.

I'm using jQuery v3.2.1

**Comment by oculus42** [comment] 2019-05-30 14:42
I'm not seeing this issue on Firefox 67, but I did experience Firefox 67 resetting support for enterprise certificates that caused issues loading pages/content.

Can you provide a JSFiddle or other example of a page where you experience the error so we can troubleshoot against that?

I tested on macOS 10.14.5 with Firefox 67.0.
What system/environment are you dealing with?

**Comment by Malavos** [comment] 2019-06-06 14:01
@mcanepa Hello there. If you are still having this issue on Fox, you should upload an JSFiddle, as stated by oculus.

I've tried printing on Fox, and had no problems whatsoever. If the problem is no longer hapenning, we should close the issue.

**Comment by mcanepa** [comment] 2019-06-06 14:34
sorry for the late reply!

I was using v1.12.3, then I've tried the latest but the same behavior was happening. I then switch to [this plugin](https://github.com/DoersGuild/jQuery.print) and had no problems.

I will try to replicate this in a jsfiddle, just give me a couple of days.

**Comment by Malavos** [comment] 2019-06-06 14:40
@mcanepa not a problem at all. Let's keep this issue open then.

**Comment by mcanepa** [comment] 2019-06-07 15:01
well here is the [fiddle](https://jsfiddle.net/8yvprujm/),

The desire output is red border and text for screen, and blue border and text for print (just a demo)

I'm also having problems with chrome. Below are screenshots with this plugin and withDoersGuild's

![1](https://user-images.githubusercontent.com/25961439/59113504-8c270300-891b-11e9-9b8a-48aa8019e592.png)
![2](https://user-images.githubusercontent.com/25961439/59113505-8c270300-891b-11e9-90eb-f30f652af1c5.png)

**Comment by jasonday** [comment] 2019-06-07 16:04
In the fiddle, if you set `debug:true` and inspect the output you'll see that the `<style>` isn't being imported - only the stylesheet. If you have `<style>` tags, you'll need to use the option `importStyle: true` to pull them into the print iframe. See example: https://jsfiddle.net/8dvy4tea/

**Comment by mcanepa** [comment] 2019-06-07 16:11
What is really driving me crazy is the fact that I didn't change one bit of my code. This happened the moment firefox upgraded from 66.0.5 to 67.

And what is more frustrating is that without changing anything, this actually work while on localhost, but fail online

I guess this can be closed then. Sorry for the inconvenience.

**Closed** 2019-06-07 16:25 UTC

**Comment by jasonday** [comment] 2019-06-07 16:29
Not a problem. It may have been environment specific due to permissions, paths, etc. as well - such as in the jsfiddle (due to how jsfiddle includes the fiddle CSS).
